# Validação de PRs:
#   - Instalar dependencias
#   - Build
#   - Testes

version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.0.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn

      - run:
          name: Build TypeScript
          command: yarn build

      - run:
          name: Run tests
          command: yarn test:cov

workflows:
  validate-pull-request:
    jobs:
      - build-and-test
